name: ' ci-cd 🤖 main '

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    quality:
        name: Quality
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure Git
              run: |
                  git config --global user.name "GitHub Action : cicd.quality"
                  git config --global user.email "bekhtari@nasag.fr"

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            # This will also run '--frozen-lockfile --prefer-offline'
            # equivalent to -> 'npm ci'
            - name: 📥 Monorepo install
              uses: ./.github/actions/pnpm-install

            - name: Format
              run: |
                  pnpm format:fix
              # add ESlint

            - name: Test
              run: |
                  pnpm test:unit
              # add Coverall

    publish:
        name: Publish
        runs-on: ubuntu-latest
        ## // if  github.ref == 'refs/heads/main'
        needs: [quality]
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure Git
              run: |
                  git config --global user.name "GitHub Action : cicd.release"
                  git config --global user.email "bekhtari@nasag.fr"

            - name: Set up Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            # This will also run '--frozen-lockfile --prefer-offline'
            # equivalent to -> 'npm ci'
            - name: 📥 Monorepo install
              uses: ./.github/actions/pnpm-install

            - name: Build
              run: pnpm build

            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  pnpm semantic-release
